portfolio/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('portfolio.views',
    # Portfolio listing
    (r'^scores/$', 'smart_list', {'type': 0}),
    (r'^scores/tag/(?P<tag>[ -_a-zA-Z0-9]+)/$', 'with_tags', {'type': 0}),
    (r'^recordings/$', 'smart_list', {'type': 1}),
    (r'^recordings/tag/(?P<tag>[ -_a-zA-Z0-9]+)/$', 'with_tags', {'type': 1}),
    (r'^writing/$', 'smart_list', {'type': 2}),
    (r'^writing/tag/(?P<tag>[ -_a-zA-Z0-9]+)/$', 'with_tags', {'type': 2}),
    (r'^graphics/$', 'smart_list', {'type': 3}),
    (r'^graphics/tag/(?P<tag>[ -_a-zA-Z0-9]+)/$', 'with_tags', {'type': 3}),
    (r'^webdesign/$', 'smart_list', {'type': 4}),
    (r'^webdesign/tag/(?P<tag>[ -_a-zA-Z0-9]+)/$', 'with_tags', {'type': 4}),
    (r'^programming/$', 'smart_list', {'type': 5}),
    (r'^programming/tag/(?P<tag>[ -_a-zA-Z0-9]+)/$', 'with_tags', {'type': 5}),
    (r'^mixed/$', 'smart_list', {'type': 6}),

    # Portfolio viewing
    (r'^(work|book|gallery|websites|package|collection)/(?P<slug>[a-zA-Z0-9_-]+)/$', 'smart_show', {'type': 6}),
    (r'^score/(?P<slug>[a-zA-Z0-9_-]+)/$', 'smart_show', {'type': 0}),
    (r'^ajax/score/(?P<slug>[a-zA-Z0-9_-]+)/$', 'score_ajax'),
    (r'^recording/(?P<slug>[a-zA-Z0-9_-]+)/$', 'smart_show', {'type': 1}),
    (r'^ajax/recording/(?P<slug>[a-zA-Z0-9_-]+)/$', 'recording_ajax'),
    (r'^ajax/collection/(?P<slug>[a-zA-Z0-9_-]+)/$', 'mp_recording_ajax'),
    (r'^(story|chapter|article|letter)/(?P<slug>[a-zA-Z0-9_-]+)/$', 'smart_show', {'type': 2}),
    (r'^(photo|graphic)/(?P<slug>[a-zA-Z0-9_-]+)/$', 'smart_show', {'type': 3}),
    (r'^website/(?P<slug>[a-zA-Z0-9_-]+)/$', 'smart_show', {'type': 4}),
    (r'^program/(?P<slug>[a-zA-Z0-9_-]+)/$', 'smart_show', {'type': 5}),
)

urls.py
from django.conf.urls.defaults import *
from store.models import *
from sitemaps import *
from django.contrib.sitemaps import FlatPageSitemap
from django.contrib import admin
admin.autodiscover()

sitemaps = {
        'products': ProductSitemap,
        'creators': CreatorSitemap,
        }

urlpatterns = patterns('',
    (r'^$', 'blog.views.front'),
    (r'^crossdomain.xml$', 'django.views.generic.simple.direct_to_template', {'template': 'flatpages/crossdomainpolicy.xml'}),
    (r'^sitemap.xml$', 'django.views.generic.simple.direct_to_template', {'template': 'flatpages/sitemap.xml'}),
    (r'^sitemap-other.xml$', 'django.views.generic.simple.direct_to_template', {'template': 'flatpages/sitemap-other.xml'}),
    (r'^sitemap-store.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    (r'^sitemap-flatpages.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': { 'flatpages': FlatPageSitemap }}),
    (r'^store/$', 'blog.views.storefront'),
    (r'^~(?P<username>[-_a-zA-Z0-9]+)/$', 'store.views.creator_detail'),
    (r'^~(?P<filter>[-_a-zA-Z0-9]+)/products/$', 'store.views.filter_products', {'filter_by': 'creator__user__username__iexact'}),
    (r'^store/', include('store.urls')),
    (r'^portfolio/', include('portfolio.urls')),
    (r'^admin/(.*)', admin.site.root),
    (r'^forums/', include('forum.urls')),

    (r'^accounts/view/(?P<username>[-_a-zA-Z0-9]+)/$', 'usermgmt.views.user_view'),
    (r'^accounts/interest/(?P<tag>[-_a-zA-Z0-9]+)/$', 'usermgmt.views.with_tags'),
    (r'^accounts/profile/$', 'usermgmt.views.user_home'),
    (r'^accounts/profile/edit/$', 'usermgmt.views.user_edit'),
    (r'^accounts/', include('registration.urls')),
    (r'^about/contact/$', 'usermgmt.views.contact')
)
        ##(r'^store/products/difficulties/$', 'difficulties') # FLATPAGE - template: store/about_flatpages.html
        ##(r'^store/products/categories/$', 'categories'), # FLATPAGE - template: store/about_flatpages.html
        ##(r'^store/products/tags/$', 'tag_cloud'), # FLATPAGE - template: store/tags.html
        ##(r'^account/interests/$', tag_cloud) # FLATPAGE - template: registration/tags.html
        #(r'^about/$') # FLATPAGE - template: flatpages/about.html
        #(r'^about/faq/$') # FLATPAGE - template: flatpages/about.html
        #(r'^about/submit/$') # FLATPAGE - template: flatpages/about.html
        #(r'^about/legal/$') # FLATPAGE - template: flatpages/about.html
        #(r'^about/ip/$') # FLATPAGE - template: flatpages/about.html
        #(r'^store/about/shipping/$') # FLATPAGE - template: flatpages/about.html
        #(r'^store/about/problems/$') # FLATPAGE - template: flatpages/about.html

portfolio/models.py
from django.db import models
from tagging.fields import TagField

STATUS = (
        ('0', 'Incomplete'),
        ('1', 'Rough Draft'),
        ('2', 'Edited'),
        ('3', 'Completed'),
        ('4', 'Abandoned')
        )

MEDIA = (
        ('0', 'Score'),
        ('1', 'Recording'),
        ('2', 'Writing'),
        ('3', 'Image'),
        ('4', 'Webdesign'),
        ('5', 'Software'),
        ('6', 'Mixed')
        )

class License(models.Model):
    slug = models.SlugField(unique = True)
    title = models.CharField(max_length = 120)
    description = models.CharField(max_length = 500)
    url = models.URLField(blank = True)
    display = models.CharField(max_length = 120)

    def __unicode__(self):
        return self.title

class MultiPart(models.Model):
    slug = models.SlugField(unique = True)
    title = models.CharField(max_length = 250)
    description = models.TextField()
    date = models.DateField()
    external_link = models.URLField(blank = True)
    status = models.CharField(max_length = 1, choices = STATUS)
    part_of_work = models.ForeignKey('MultiPart', blank = True, null = True)
    media = models.CharField(max_length = 1, choices = MEDIA)
    license = models.ForeignKey('License', blank = True, null = True)
    tags = TagField()

    def __unicode__(self):
        return "%s (%s)" % (self.title, self.get_media_display())

    class Meta:
        ordering = ['media', 'title']

class Score(models.Model):
    slug = models.SlugField(unique = True)
    title = models.CharField(max_length = 250)
    description = models.TextField()
    instrumentation = models.CharField(max_length = 120)
    date = models.DateField()
    duration = models.DecimalField(max_digits = 5, decimal_places = 2)
    sib_file = models.FileField(blank = True, null = True, upload_to = 'sibData')
    pdf_file = models.FileField(blank = True, null = True, upload_to = 'pdfData')
    part_of_work = models.ForeignKey('MultiPart', blank = True, null = True)
    external_link = models.URLField(blank = True)
    status = models.CharField(max_length = 1, choices = STATUS)
    license = models.ForeignKey('License', blank = True, null = True)
    tags = TagField()

    def __unicode__(self):
        return "%s (Score)" % self.title

    class Meta:
        ordering = ['title']

class Recording(models.Model):
    slug = models.SlugField(unique = True)
    title = models.CharField(max_length = 250)
    source = models.CharField(max_length = 250, blank = True)
    performer = models.CharField(max_length = 250, blank = True)
    description = models.TextField()
    date = models.DateField()
    music_file = models.FileField(upload_to = 'mp3Data')
    duration = models.DecimalField(max_digits = 5, decimal_places = 2)
    score = models.ForeignKey('Score', blank = True, null = True)
    part_of_work = models.ForeignKey('MultiPart', blank = True, null = True)
    external_link = models.URLField(blank = True)
    status = models.CharField(max_length = 1, choices = STATUS)
    license = models.ForeignKey('License', blank = True, null = True)
    tags = TagField()

    def __unicode__(self):
        return "%s (Recording)" % self.title

    class Meta:
        ordering = ['title']

class Writing(models.Model):
    TYPE = (
            ('s', 'story'),
            ('c', 'chapter'),
            ('a', 'article'),
            ('l', 'letter')
            )
    slug = models.SlugField(unique = True)
    title = models.CharField(max_length = 250)
    type = models.CharField(max_length = 1, choices = TYPE)
    description = models.TextField()
    date = models.DateField()
    full_text = models.TextField()
    part_of_work = models.ForeignKey('MultiPart', blank = True, null = True)
    external_link = models.URLField(blank = True)
    status = models.CharField(max_length = 1, choices = STATUS)
    license = models.ForeignKey('License', blank = True, null = True)
    tags = TagField()

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['title']

class Image(models.Model):
    TYPE = (
            ('p', 'Photograph'),
            ('d', 'Graphic design')
            )
    slug = models.SlugField(unique = True)
    title = models.CharField(max_length = 250)
    description = models.TextField()
    date = models.DateField()
    image = models.ImageField(upload_to = 'imageData')
    thumb = models.ImageField(upload_to = 'imageData/thumbs', blank = True, null = True)
    type = models.CharField(max_length = 1, choices = TYPE)
    part_of_work = models.ForeignKey('MultiPart', blank = True, null = True)
    external_link = models.URLField(blank = True)
    status = models.CharField(max_length = 1, choices = STATUS)
    license = models.ForeignKey('License', blank = True, null = True)
    tags = TagField()

    def __unicode__(self):
        return '%s (Image)' % self.title

    class Meta:
        ordering = ['title']

class Website(models.Model):
    slug = models.SlugField(unique = True)
    title = models.CharField(max_length = 250)
    description = models.TextField()
    date = models.DateField()
    image = models.ImageField(upload_to = 'websiteData')
    part_of_work = models.ForeignKey('MultiPart', blank = True, null = True)
    external_link = models.URLField()
    status = models.CharField(max_length = 1, choices = STATUS)
    license = models.ForeignKey('License', blank = True, null = True)
    tags = TagField()

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['title']

class Program(models.Model):
    slug = models.SlugField(unique = True)
    title = models.CharField(max_length = 250)
    description = models.TextField()
    date = models.DateField()
    image = models.ImageField(upload_to = 'programData', blank = True, null = True)
    file = models.FileField(upload_to = 'programData', blank = True, null = True)
    part_of_work = models.ForeignKey('MultiPart', blank = True, null = True)
    external_link = models.URLField(blank = True)
    status = models.CharField(max_length = 1, choices = STATUS)
    license = models.ForeignKey('License', blank = True, null = True)
    tags = TagField()

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['title']

portfolio/views.py
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from portfolio.models import *

def smart_list(request, type):
    objects = (Score,
               Recording,
               Writing,
               Image,
               Website,
               Program)[type].objects.filter(part_of_work__isnull = True)
    mps = MultiPart.objects.filter(media = str(type))
    return render_to_response('portfolio/%s_list.html' % MEDIA[type][1].lower(), context_instance = RequestContext(request, {'objects': objects, 'mps': mps}))

def with_tags(request, tag, type):
    tag = tag.replace('_', ' ')
    query = get_object_or_404(Tag, name = tag)
    objects = TaggedItem.objects.get_by_model((Score, Recording, Writing, Image, Website, Program)[type], query)
    return render_to_response('portfolio/%s_list_by_tag.html' % MEDIA[type][1].lower(), context_instance = RequestContext(request, {'objects': objects}))

def smart_show(request, slug, type):
    object = get_object_or_404((Score, Recording, Writing, Image, Website, Program, MultiPart)[type], slug = slug)
    if type == 6: # MultiPart
        if (request.method == 'GET') and (request.GET.get('asx', None) == 'true'):
            return render_to_response('portfolio/playlist.xml', context_instance = RequestContext(request, {'mp_object': object}))
        else:
            return render_to_response('portfolio/mp_%s_detail.html' % object.get_media_display().lower(), context_instance = RequestContext(request, {'mp_object': object}))
    else: 
        if (request.method == 'GET') and (request.GET.get('asx', None) == 'true'):
            return render_to_response('portfolio/playlist.xml', context_instance = RequestContext(request, {'mp_object': (object)}))
        else:
            return render_to_response('portfolio/%s_detail.html' % MEDIA[type][1].lower(), context_instance = RequestContext(request, {'object': object}))

def score_ajax(request, slug):
    return render_to_response('portfolio/score_ajax.html', context_instance = RequestContext(request, {'object': get_object_or_404(Score, slug = slug)}))

def recording_ajax(request, slug):
    return render_to_response('portfolio/recording_ajax.html', context_instance = RequestContext(request, {'object': get_object_or_404(Recording, slug = slug)}))

def mp_recording_ajax(request, slug):
    return render_to_response('portfolio/mp_recording_ajax.html', context_instance = RequestContext(request, {'object': get_object_or_404(MultiPart, slug = slug)}))

templates/portfolio/image_detail.html
{% extends "base.html" %}

{% block title %}{{ object.get_type_display }}: {{ object.title }}{% endblock %}

{% block header %}{{ object.get_type_display}}: {{ object.title }}{% endblock %}

{% block content %}
<img src="http://media.drab-makyo.com/{{ object.image }}" style="display: block; margin: auto" /><br clear="all" />
<p>
{{ object.description|safe }}
</p>

<ul>
    <li><strong>Date:</strong> {{ object.date }}</li>
    <li><strong>Part of multi-part work:</strong> {% if object.part_of_work %}<a href="/gallery/{{ object.part_of_work.slug }}/">{{ object.part_of_work.title }}</a>{% else %}<em>N/A</em>{% endif %}</li>
    <li><strong>External link:</strong> {% if object.external_link %}<a href="{{ object.external_link }}" target="_blank">{{ object.external_link }}</a>{% else %}<em>N/A</em>{% endif %}</li>
</ul>

{% include "portfolio/license.html" %}
{% endblock %}

templates/portfolio/image_list.html
{% extends "base.html" %}

{% block title %}Images{% endblock %}

{% block header %}Images{% endblock %}

{% block content %}
<table border="0" width="100%">
{% for object in objects %}
    {% cycle "<tr class=\"odd\">" "" "" "" "<tr class=\"even\">" "" "" "" %}
    <td align="center" class="{% cycle "odd" "even" %}"><a href="/{% ifequal object.type "p" %}photo{% else %}graphic{% endifequal %}/{{ object.slug }}/"><img src="http://media.drab-makyo.com/{{ object.thumb }}" /><br />
            {{ object.title }}</a></td>
    {% cycle "" "" "" "</tr>" %}
{% endfor %}
</table>

{% ifnotequal mps.count 0 %}
<h3>Sets</h3>
<ul>
    {% for mp in mps %}
    <li class="{% cycle "odd" "even"%}"><a href="/gallery/{{ mp.slug }}/">{{ mp.title }}</a> - {{ mp.description|safe|truncatewords_html:25 }}</li>
    {% endfor %}
</ul>
{% endifnotequal %}
{% endblock %}

templates/portfolio/mp_image_detail.html
{% extends "base.html" %}

{% block title %}Images in {{ mp_object.title }}{% endblock %}

{% block header %}Images in {{ mp_object.title }}{% endblock %}

{% block content %}
<table border="0">
{% for object in mp_object.image_set.all %}
    {% cycle "<tr>" "" "" "" %}
        <td><a href="/{% ifequal object.type "p" %}photo{% else %}graphic{% endif %}/{{ object.slug }}/"><img src="{{ object.thumb }}" /><br />
            {{ object.title }}</a></td>
    {% cycle "" "" "" "</tr>" %}
{% endfor %}
{% endblock %}

templates/portfolio/mp_recording_detail.html
{% extends "base.html" %}

{% block title %}Recordings in {{ mp_object.title }}{% endblock %}

{% block header %}Recordings in {{ mp_object.title }}{% endblock %}

{% block content %}
<p>{{ mp_object.description|safe }}<br /><a href="#playall">Play all in set</a></p>
<p>
<ul>
    <li><strong>Date:</strong> {{ mp_object.date|date:"F Y" }}</li>
    <li><strong>Status:</strong> {{ mp_object.get_status_display }}</li>
    <li><strong>External link:</strong> {% if mp_object.external_link %}<a href="{{ mp_object.external_link }}">Available</a>{% else %}<em>N/A</em>{% endif %}</li>
</ul>
</p>
<hr width="50%" />
<ul>
    {% for object in mp_object.recording_set.all %}
    <li class="{% cycle "odd" "even"%}"><a href="/recording/{{ object.slug }}/">{{ object.title }}</a> - {{ object.description|safe|truncatewords_html:25 }}</li>
    {% endfor %}
</ul>
<hr width="50%" />
<a name="playall"></a>
<h3>Play set</h3>
<a style="border: 1px solid #ccc; background-color: #ddd" target="dmplayer" href="/ajax/collection/{{ mp_object.slug }}" onClick="window.open('/ajax/collection/{{ mp_object.slug }}', 'dmplayer', 'status=yes,menubar=no,toolbar=no,location=no,directories=no,resizable=no,scrollbars=no,height=230,width=500')">Launch in separate window</a>
<script type='text/javascript' src='http://media.drab-makyo.com/js/swfobject.js'></script>
 
<div id='mediaspace'>This text will be replaced</div>
 
<script type='text/javascript'>
    var so = new SWFObject('http://media.drab-makyo.com/player.swf','ply','470','204','9','#ffffff');
    so.addParam('allowfullscreen','true');
    so.addParam('allowscriptaccess','always');
    so.addParam('wmode','opaque');
    so.addVariable('playlistfile','/collection/{{ mp_object.slug }}/%3Fasx%3dtrue');
    so.addVariable('playlist','bottom');
    so.addVariable('repeat','list');
    so.write('mediaspace');
</script>

{% include "portfolio/mp_license.html" %}
{% endblock %}

templates/portfolio/mp_score_detail.html
{% extends "base.html" %}

{% block title %}Scores in {{ mp_object.title }}{% endblock %}

{% block header %}Scores in {{ mp_object.title }}{% endblock %}

{% block content %}
<p>{{ mp_object.description|safe }}</p>
<p>
<ul>
    <li><strong>Date:</strong> {{ mp_object.date|date:"F Y" }}</li>
    <li><strong>Status:</strong> {{ mp_object.get_status_display }}</li>
    <li><strong>External link:</strong> {% if mp_object.external_link %}<a href="{{ mp_object.external_link }}">Available</a>{% else %}<em>N/A</em>{% endif %}</li>
</ul>
</p>
<hr width="50%" />
<ul>
    {% for object in mp_object.score_set.all %}
    <li class="{% cycle "odd" "even"%}"><a href="/score/{{ object.slug }}/">{{ object.title }}</a> - {{ object.instrumentation }} <br />
    <p>{{ object.description|safe|truncatewords_html:25 }}</p></li>
    {% endfor %}
</ul>

{% include "portfolio/mp_license.html" %}
{% endblock %}

templates/portfolio/mp_software_detail.html
{% extends "base.html" %}

{% block title %}Programs in {{ mp_object.title }}{% endblock %}

{% block header %}Programs in {{ mp_object.title }}{% endblock %}

{% block content %}
<ul>
    {% for object in mp_object.program_set.all %}
    <li class="{% cycle "odd" "even"%}"><a href="/program/{{ object.slug }}/">{{ object.title }}</a> - {{ object.description|safe|truncatewords_html:2 }}</li>
    {% endfor %}
</ul>
{% endblock %}

templates/portfolio/mp_writing_detail.html
{% extends "base.html" %}

{% block title %}Writings in {{ mp_object.title }}{% endblock %}

{% block header %}Writings in {{ mp_object.title }}{% endblock %}

{% block content %}
<ul>
    {% for object in mp_object.writing_set.all %}
    <li class="{% cycle "odd" "even"%}"><a href="/{{ object.type }}/{{ object.slug }}/">{{ object.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

templates/portfolio/recording_detail.html
{% extends "base.html" %}

{% block title %}Recording: {{ object.title }}{% endblock %}

{% block header %}Recording: {{ object.title }}{% endblock %}

{% block content %}
<script type='text/javascript' src='http://media.drab-makyo.com/js/swfobject.js'></script>
 
<div id='mediaspace'>This text will be replaced</div>
<a style="border: 1px solid #ccc; background-color: #ddd" target="dmplayer" href="/ajax/recording/{{ object.slug }}" onClick="window.open('/ajax/recording/{{ object.slug }}', 'dmplayer', 'status=yes,menubar=no,toolbar=no,location=no,directories=no,resizable=no,scrollbars=no,height=230,width=500')">Launch in separate window</a>
 
<script type='text/javascript'>
    var so = new SWFObject('http://media.drab-makyo.com/player.swf','mpl','470','24','9');
    so.addParam('allowfullscreen','true');
    so.addParam('allowscriptaccess','always');
    so.addParam('wmode','opaque');
    so.addVariable('file','http://media.drab-makyo.com/{{ object.music_file }}');
    so.addVariable('title','{{ object.title }}');
    so.write('mediaspace');
</script>
<p>
{{ object.description|safe }}
</p>

<ul>
    <li><strong>Date:</strong> {{ object.date }}</li>
    <li><strong>Source:</strong> {% if object.source %}{{ object.source }}{% else %}<em>N/A</em>{% endif %}</li>
    <li><strong>Performer:</strong> {% if object.performer %}{{ object.performer }}{% else %}<em>N/A</em>{% endif %}</li>
    <li><strong>Score:</strong> {% if object.score %}<a href="/score/{{ object.score.slug }}">Available</a>{% else %}<em>N/A</em>{% endif %}</li>
    <li><strong>Duration:</strong> {{ object.duration }} minutes</li>
    <li><strong>Status:</strong> {{ object.get_status_display }}</li>
    <li><strong>Part of multi-part work:</strong> {% if object.part_of_work %}<a href="/gallery/{{ object.part_of_work.slug }}/">{{ object.part_of_work.title }}</a>{% else %}<em>N/A</em>{% endif %}</li>
    <li><strong>External link:</strong> {% if object.external_link %}<a href="{{ object.external_link }}" target="_blank">{{ object.external_link }}</a>{% else %}<em>N/A</em>{% endif %}</li>
</ul>

{% include "portfolio/license.html" %}
{% endblock %}

templates/portfolio/score_detail.html
{% extends "base.html" %}

{% block title %}Score: {{ object.title }}{% endblock %}

{% block header %}Score: {{ object.title }}{% endblock %}

{% block content %}
{% if object.sib_file %}
<a style="border: 1px solid #ccc; background-color: #ddd;" href="javascript:" onClick="$('div.hideplugin object').length?$('div.hideplugin').toggle('slow'):$('div.hideplugin').load('http://drab-makyo.com/ajax/score/{{ object.slug }}')&&$('div.hideplugin').toggle('slow');">Show/Hide Sibelius Scorch version of {{object.title}}</a> - <a style="border: 1px solid #ccc; background-color: #ddd;" href="/ajax/score/{{ object.slug }}/" target="_blank">Open in new window/tab</a>
<div class="hideplugin">
</div>
{% endif %}
<p>
{{ object.description|safe }}
</p>

<ul>
    <li><strong>Date:</strong> {{ object.date|date:"F, Y" }}</li>
    <li><strong>Instrumentation:</strong> {{ object.instrumentation }}</li>
    <li><strong>Duration:</strong> {{ object.duration }} minutes</li>
    <li><strong>Printable PDF:</strong> {% if object.pdf_file %}<a href="http://media.drab-makyo.com/{{ object.pdf_file }}" target="_blank">Available</a>{% else %}<em>N/A</em>{% endif %}</li>
    <li><strong>Recordings:</strong> {% for rec in object.recording_set.all %}<a href="/recording/{{ rec.slug }}/">{% if rec.performer %}{{ rec.performer }}{% else %}{% if rec.source %}{{ rec.source }}{% else %}[ {{ rec.id }} ]{% endif %}{% endif %}</a> {% endfor %}</li>
    <li><strong>Status:</strong> {{ object.get_status_display }}</li>
    <li><strong>Part of multi-part work:</strong> {% if object.part_of_work %}<a href="/gallery/{{ object.part_of_work.slug }}/">{{ object.part_of_work.title }}</a>{% else %}<em>N/A</em>{% endif %}</li>
    <li><strong>External link:</strong> {% if object.external_link %}<a href="{{ object.external_link }}" target="_blank">{{ object.external_link }}</a>{% else %}<em>N/A</em>{% endif %}</li>
</ul>

{% include "portfolio/license.html" %}
{% endblock %}

templates/portfolio/software_detail.html
{% extends "base.html" %}

{% block title %}Program: {{ object.title }}{% endblock %}

{% block header %}Program: {{ object.title }}{% endblock %}

{% block content %}
{% if object.image %}<img src="http://media.drab-makyo.com/{{ object.image }}" style="display: block; margin: auto; width: 50%" /><br clear="all" />{% endif %}
<p>
{{ object.description|safe }}
</p>

<ul>
    <li><strong>File download:</strong> {% if object.file %}<a href="http://media.drab-makyo.com/{{ object.file }}" target="_blank">Available</a>{% else %}<em>N/A</em>{% endif %}</li>
    <li><strong>Date:</strong> {{ object.date }}</li>
    <li><strong>Status:</strong> {{ object.get_status_display }}</li>
    <li><strong>Part of multi-part work:</strong> {% if object.part_of_work %}<a href="/package/{{ object.part_of_work.slug }}/">{{ object.part_of_work.title }}</a>{% else %}<em>N/A</em>{% endif %}</li>
    <li><strong>External link:</strong> {% if object.external_link %}<a href="{{ object.external_link }}" target="_blank">{{ object.external_link }}</a>{% else %}<em>N/A</em>{% endif %}</li>
</ul>

{% include "portfolio/license.html" %}
{% endblock %}

templates/portfolio/writing_detail.html
{% extends "base.html" %}

{% block title %}Writing: {{ object.title }}{% endblock %}

{% block header %}Writing: {{ object.title }}{% endblock %}

{% block content %}
<p>
{{ object.description|safe }}
</p>

<ul>
    <li>Date: {{ object.date }}</li>
    <li>Status: {{ object.get_status_display }}</li>
    <li>Part of multi-part work: {% if object.part_of_work %}<a href="/gallery/{{ object.part_of_work.slug }}/">{{ object.part_of_work.title }}</a>{% else %}<em>N/A</em>{% endif %}</li>
    <li>External link: {% if object.external_link %}<a href="{{ object.external_link }}" target="_blank">{{ object.external_link }}</a>{% else %}<em>N/A</em>{% endif %}</li>
</ul>

<div class="fulltext">
    {{ object.full_text }}
</div>

<p><a href="{{object.license.url }}" target="_blank" alt="{{object.license.title }}">{{ object.license.display|safe }} Matthew Scott {{ object.date|date:"Y" }}</a> - {{ object.license.description|safe }}</p>
{% endblock %}