store/ledger/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('store.ledger.views',
        (r'^$', 'front'),
        (r'^creators/$', 'creators'),
        (r'^creator/(?P<filter>[-_a-zA-Z0-9]+)/$', 'filter_ledger', {'filter_by': 'cart__item_set__product__creator__user__username__exact', 'type': 'creator'}),
        (r'^products/$', 'products'),
        (r'^product/(?P<filter>[-_a-zA-Z0-9]+)/$', 'filter_ledger', {'filter_by': 'cart__item_set__product__sku__exact', 'type': 'product'}),
        (r'^business/$', 'filter_ledger', {}), # should return whole set
)

#query string
#  startdate=yyyy-mm-dd
#  duration=(day|week|month*|quarter|year|all)
#  format=(html*|latex|csv)
#  depth=(summary*|clean|full)
#    summary=number of transactions, amount earned/lost, etc
#    clean=summary plus individual transactions with no specific details
#    full=summary plus individual transactions with details

store/urls.py
from django.conf.urls.defaults import *
from store.models import *

urlpatterns = patterns('store.views',
        (r'^googlecheckout/$', 'gc_callback'),

        (r'^product/(?P<slug>[a-z0-9_-]+)/$', 'product_detail'),

        (r'^products/difficulty/(?P<filter>[1-7])/$', 'filter_products', {'filter_by': 'difficulty__exact'}),
        (r'^products/category/(?P<filter>[A-G])/$', 'filter_products', {'filter_by': 'category__iexact'}),
        (r'^products/ensembles/$', 'list_fields', {'field': 'ensemble'}),
        (r'^products/ensemble/(?P<filter>.+)/$', 'filter_products', {'filter_by': 'ensemble__iexact'}),
        (r'^products/instrumentations/$', 'list_fields', {'field': 'instrumentation'}),
        (r'^products/instrumentation/(?P<filter>.+)/$', 'filter_products', {'filter_by': 'instrumentation__iexact'}),
        (r'^products/tag/(?P<tag>[-_a-zA-Z0-9]+)/$', 'with_tags'),
        (r'^products/creators/$', 'creators'),
        (r'^products/creator/(?P<filter>[-_a-zA-Z0-9]+)/$', 'filter_products', {'filter_by': 'creator__user__username__iexact'}),

        (r'^creator/(?P<username>[-_a-zA-Z0-9]+)/$', 'creator_detail'),

        (r'^carts/$', 'cart_list'),
        (r'^cart/(?P<object_id>\d+)/$', 'cart_handler'),
        (r'^cart/add/$', 'create_cart'),
        (r'^ledger/', include('store.ledger.urls')),
)

urls.py
from django.conf.urls.defaults import *
from store.models import *
from sitemaps import *
from django.contrib.sitemaps import FlatPageSitemap
from django.contrib import admin
admin.autodiscover()

sitemaps = {
        'products': ProductSitemap,
        'creators': CreatorSitemap,
        }

urlpatterns = patterns('',
    (r'^$', 'blog.views.front'),
    (r'^crossdomain.xml$', 'django.views.generic.simple.direct_to_template', {'template': 'flatpages/crossdomainpolicy.xml'}),
    (r'^sitemap.xml$', 'django.views.generic.simple.direct_to_template', {'template': 'flatpages/sitemap.xml'}),
    (r'^sitemap-other.xml$', 'django.views.generic.simple.direct_to_template', {'template': 'flatpages/sitemap-other.xml'}),
    (r'^sitemap-store.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    (r'^sitemap-flatpages.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': { 'flatpages': FlatPageSitemap }}),
    (r'^store/$', 'blog.views.storefront'),
    (r'^~(?P<username>[-_a-zA-Z0-9]+)/$', 'store.views.creator_detail'),
    (r'^~(?P<filter>[-_a-zA-Z0-9]+)/products/$', 'store.views.filter_products', {'filter_by': 'creator__user__username__iexact'}),
    (r'^store/', include('store.urls')),
    (r'^portfolio/', include('portfolio.urls')),
    (r'^admin/(.*)', admin.site.root),
    (r'^forums/', include('forum.urls')),

    (r'^accounts/view/(?P<username>[-_a-zA-Z0-9]+)/$', 'usermgmt.views.user_view'),
    (r'^accounts/interest/(?P<tag>[-_a-zA-Z0-9]+)/$', 'usermgmt.views.with_tags'),
    (r'^accounts/profile/$', 'usermgmt.views.user_home'),
    (r'^accounts/profile/edit/$', 'usermgmt.views.user_edit'),
    (r'^accounts/', include('registration.urls')),
    (r'^about/contact/$', 'usermgmt.views.contact')
)
        ##(r'^store/products/difficulties/$', 'difficulties') # FLATPAGE - template: store/about_flatpages.html
        ##(r'^store/products/categories/$', 'categories'), # FLATPAGE - template: store/about_flatpages.html
        ##(r'^store/products/tags/$', 'tag_cloud'), # FLATPAGE - template: store/tags.html
        ##(r'^account/interests/$', tag_cloud) # FLATPAGE - template: registration/tags.html
        #(r'^about/$') # FLATPAGE - template: flatpages/about.html
        #(r'^about/faq/$') # FLATPAGE - template: flatpages/about.html
        #(r'^about/submit/$') # FLATPAGE - template: flatpages/about.html
        #(r'^about/legal/$') # FLATPAGE - template: flatpages/about.html
        #(r'^about/ip/$') # FLATPAGE - template: flatpages/about.html
        #(r'^store/about/shipping/$') # FLATPAGE - template: flatpages/about.html
        #(r'^store/about/problems/$') # FLATPAGE - template: flatpages/about.html

store/models.py
from django.db import models
from django.contrib.auth.models import User
from store.checkout import get_controller
from tagging.fields import TagField

class Creator(models.Model):
    user = models.ForeignKey(User)
    profile = models.TextField()
    website = models.URLField(blank = True)

    def __unicode__(self):
        return self.user.get_full_name()

    def get_absolute_url(self):
        return "/store/creator/%s/" % self.user.username

class Product(models.Model):
    # Checkout stuff
    STATUS_CHOICES = (
            ('0', 'Live'),
            ('1', 'Coming Soon'),
            ('2', 'Out-of-Print'),
            ('3', 'Hidden')
            )

    sku = models.SlugField()
    status = models.CharField(max_length = 1, choices = STATUS_CHOICES)
    name = models.CharField(max_length = 250)
    short_desc = models.CharField(max_length = 500)
    width = models.DecimalField(max_digits = 3, decimal_places = 1)
    length = models.DecimalField(max_digits = 3, decimal_places = 1)
    height = models.DecimalField(max_digits = 3, decimal_places = 1)
    weight = models.DecimalField(max_digits = 3, decimal_places = 1)
    price = models.DecimalField(max_digits = 6, decimal_places = 2)

    # Product stuff
    DIFFICULTY_CHOICES = (
            ('1', 'Grade 1'),
            ('2', 'Grade 2'),
            ('3', 'Grade 3'),
            ('4', 'Grade 4'),
            ('5', 'Grade 5'),
            ('6', 'Grade 6'),
            ('7', 'Grade 7')
            )

    CATEGORY_CHOICES = (
            ('A', 'Concert'),
            ('B', 'Sacred'),
            ('C', 'Occasional'),
            ('D', 'Educational'),
            ('E', 'Jazz'),
            ('F', 'Pop/Rock'),
            ('G', 'Textbooks/Classroom Materials'),
            ('H', 'Other')
            )

    long_desc = models.TextField()
    creator = models.ForeignKey('Creator')
    pages = models.IntegerField()
    duration = models.DecimalField(max_digits = 4, decimal_places = 1)
    difficulty = models.CharField(max_length = 1, choices = DIFFICULTY_CHOICES)
    category = models.CharField(max_length = 1, choices = CATEGORY_CHOICES)
    ensemble = models.CharField(max_length = 120)
    instrumentation = models.CharField(max_length = 120)
    tags = TagField()

    def get_unique(self, field):
        # this is bad, but it works
        from django.db import connection
        cursor = connection.cursor()
        cursor.execute("select distinct " + field.split(' ')[0] + " from store_product")
        if cursor.rowcount == -1:
            return None
        else:
            rows = cursor.fetchall()
            for i in range(0,len(rows)):
                rows[i] = str(rows[i][0])
            return rows

    def get_duration_display(self):
        import math
        hours = 0
        minutes = 0
        seconds = 0
        if self.duration > 60:
            hours = int(math.floor(self.duration / 60))
        minutes = int(math.floor(self.duration))
        seconds = int(60 * (self.duration - minutes))
        return "%02d:%02d:%02d" % (hours, minutes, seconds)

    def __unicode__(self):
        return "MJS-MP#%(sku)s - %(name)s" % {'sku': self.sku, 'name': self.name}

    def get_absolute_url(self):
        return "/store/product/%s/" % self.sku

    class Meta:
        ordering = ['sku']

class Sample(models.Model):
    TYPE_CHOICES = (
            ('A', 'Audio sample'),
            ('D', 'Page sample'),
            ('V', 'Video sample'),
            ('E', 'External sample'),
            )
    product = models.ForeignKey('Product')
    type = models.CharField(max_length = 1, choices = TYPE_CHOICES)
    url = models.URLField()

    def __unicode__(self):
        return "%s - %s" % (self.product, self.get_type_display())

    def html(self):
        ext = self.url[len(self.url) - 3:]
        if ext == 'mp3':
            return '<embed src="http://media.mjs-publishing.com/mediaplayer.swf" width="470" height="20" allowscriptaccess="always" allowfullscreen="true" flashvars="height=20&width=470&file=%s" />' % self.url
        elif ext == 'pdf':
            return '<a target="_blank" href="%s"><img src="http://media.mjs-publishing.com/pdfData/pdficon_large.gif" alt="[PDF]" width="20" /> [View Document]</a><br />Requires Adobe Reader:<br /><a href="http://get.adobe.com/reader/"><img src="http://media.mjs-publishing.com/pdfData/get_adobe_reader.gif" alt="[get Adobe Reader]" /></a>' % self.url
        else:
            return '<a target="_blank" href="%s">External Sample</a>' % self.url

        class Meta:
            ordering = ['id']

class Item(models.Model):
    cart = models.ForeignKey('Cart')
    product = models.ForeignKey('Product')
    quantity = models.IntegerField()

class Cart(models.Model):
    STATUS_CHOICES = (
            ('0', 'Finished Shopping'),
            ('1', 'Still Shopping'),
            ('2', 'System Error'),
            ('3', 'User reported problem'),
            ('4', 'Offline Order'),
            )

    owner = models.ForeignKey(User)
    name = models.CharField(max_length = 125)
    is_active = models.OneToOneField(User, null = True, blank = True, related_name = 'active_cart')
    is_shared = models.BooleanField(default = False)
    ctime = models.DateTimeField(auto_now_add = True, blank = False)
    mtime = models.DateTimeField(auto_now = True, blank = False)
    local_status = models.CharField(max_length = 1, choices = STATUS_CHOICES)
    state = models.CharField(max_length = 16, blank = True)
    payment = models.CharField(max_length = 16, blank = True)
    google_id = models.CharField(max_length = 255, blank = True)
    cart_xml = models.TextField(blank = True)
    
    
    def get_cart(self):
        from gchecky.model import *
        controller = get_controller()

        return controller.prepare_order(
                order = checkout_shopping_cart_t(
                    shopping_cart = shopping_cart_t(
                        items = [
                            item_t(
                               name = item.product.name,
                               description = item.product.short_desc,
                               unit_price = price_t(
                                   value = float(item.product.price),
                                   currency = 'USD'
                                   ),
                               item_weight = item_weight_t(
                                   value = float(item.product.weight),
                                   unit = 'LB'
                                   ),
                               quantity = item.quantity,
                               merchant_item_id = item.product.sku
                               ) for item in self.item_set.all()
                            ],
                        merchant_private_data = self.id
                        ),
                    checkout_flow_support = checkout_flow_support_t(
                        #XXX
                        edit_cart_url = 'http://sandbox.mjs-publishing.com/store/cart/%s/?action=decheckout' % self.id,
                        continue_shopping_url = 'http://sandbox.mjs-publishing.com/store/',
                        #/XXX
                        #tax_tables = tax_tables_t(
                        #    merchant_calculated = False,
                        #    default = default_tax_table_t(
                        #        tax_rules = [
                        #            default_tax_rule_t(
                        #                shipping_taxed = True,
                        #                rate = 0.059,
                        #                tax_area = tax_area_t(
                        #                    us_zip_pattern = '805*'
                        #                    )
                        #                ),
                        #            default_tax_rule_t(
                        #                shipping_taxed = True,
                        #                rate = 0.029,
                        #                tax_area = tax_area_t(
                        #                    us_state = 'CO'
                        #                    )
                        #                )
                        #            ]
                        #        )
                        #    ),
                        shipping_methods = shipping_methods_t(
                            carrier_calculated_shippings = [
                                carrier_calculated_shipping_t(
                                    carrier_calculated_shipping_options = [
                                        carrier_calculated_shipping_option_t(
                                            price = price_t(
                                                value = (self.total_weight() * 2 + 3),
                                                currency = 'USD'
                                                ),
                                            shipping_company = 'USPS',
                                            carrier_pickup = 'DROP_OFF',
                                            shipping_type = 'Priority Mail'
                                            ),
                                        carrier_calculated_shipping_option_t(
                                            price = price_t(
                                                value = (self.total_weight() * 0.5 + 6.79),
                                                currency = 'USD'
                                                ),
                                            shipping_company = 'FedEx',
                                            carrier_pickup = 'DROP_OFF',
                                            shipping_type = 'Ground'
                                            )
                                        ],
                                    shipping_packages = [
                                        shipping_package_t(
                                            height = measure_t(

templates/store/base.html
{% extends "base.html" %}

{% block section %}Store{% endblock %}

{% block sectionlinks%}
{% if user.is_authenticated %}
{% ifnotequal user.active_cart '' %}
<div id="cart-control">
    Your active cart: <a href="/store/cart/{{ user.active_cart.id }}/">${{ user.active_cart.get_total }}</a>
</div>
{% endifnotequal %}
{% endif %}
<ul>
    <li><a href="/store/">Store Home</a></li>
    <li><a href="/store/products/categories/">Categories</a></li>
    <li><a href="/store/products/difficulties/">Difficulty Levels</a></li>
    <li><a href="/store/products/ensembles/">Ensembles</a></li>
    <li><a href="/store/products/creators/">Authors and Composers</a></li>
    <li><a href="/store/products/tags/">Tags</a></li>
    {% if user.is_authenticated %}<li><a href="/store/carts/">Your Carts</a></li>{% endif %}
</ul>
{% endblock %}

templates/store/cart_confirm_delete.html
{% extends "store/base.html" %}

{% block title %}Confirm Delete{% endblock %}

{% block header %}Please confirm delete{% endblock %}
{% block content %}
<div class="warning">
    Are you sure you want to delete cart '{{ cart.name }}'?
</div>

<p style="text-align: center"<a href="{{ request.path }}?action=delete&confirm=yes">Yes</a> | <strong><a href="/store/carts/">No</a></strong></p>

{% include "store/limited_cart_table.inc" %}

{% endblock %}

templates/store/cart_detail.html
{% extends "store/base.html" %}

{% block title %}Cart: {{ cart.name }}{% endblock %}

{% block header %}Cart: {{ cart.name }} - {{ cart.get_local_status_display }}{% endblock %}

{% block content %}
<table id="cart-metadata">
    <tr>
        <th>Active status <span style="font-size: 75%; font-weight: normal">[<a>?</a>]</span></th>
        <td>{% if cart.is_active %}This cart is your active cart{% else %}This is not your active cart (<a href="/store/cart/{{ user.active_cart.id }}/">here it is!</a>)<br />
            <form id="activate-cart" method="get" action="">
                <input type="hidden" name="action" value="activate" />
                <input type="submit" value="Make this your active cart" />
            </form>{% endif %}
        </td>
    </tr>
    <tr>
        <th>Shared status <span style="font-size: 75%; font-weight: normal">[<a>?</a>]</span></th>
        <td>{% if cart.is_shared %}This cart is publicly viewable; feel free to share the URL.<br /><a href="/store/cart/{{ cart.id }}/?action=unshare">Make this cart private</a>{% else %}This cart is private - only you can see it and its contents.<br /><a href="/store/cart/{{ cart.id }}/?action=share">Make this cart publicly viewable</a>{% endif %}</td>
    </tr>
    <tr>
        <form id="delete-cart" method="post" action="?action=delete">
            <th><label for="delete">Delete this cart</label></th>
            <td><input type="submit" value="Delete this cart"></td>
        </form>
    </tr>
    <tr>
        <form id="rename-cart" method="post" action="?action=rename">
            <th><label for="newname">Rename this cart</label></th>
            <td><input type="text" name="newname" size="15" maxlength="125" /><br /><input type="submit" value="Rename Cart" /></td>
        </form>
    </tr>
</table>

<table id="cart-data">
    <thead>
        <th>Remove</th>
        <th style="text-align: left">Item/Description</th>
        <th>Price</th>
        <th>Quantity</th>
    </thead>
<form method="post" action="?action=update">
    <tbody>
        {% for item in cart.item_set.all %}
        <tr class="{% cycle 'odd' 'even' %}">
            <td width="10%" style="text-align: center"><input type="checkbox" name="remove" value="{{ item.id }}" /></td>
            <td><a href="/store/product/{{ item.product.sku }}/">{{ item.product.name }}</a><br />
                <span class="product-metadata">{{ item.product.short_desc }}</span></td>
            <td width="10%" style="text-align: center">${{ item.product.price }} ea.</td>
            <td width="10%" style="text-align: center">&times;<input type="text" size="2" name="q{{ item.id }}" value="{{ item.quantity }}" /></td>
        </tr>
        {% endfor %}
        {% if not cart.item_set.all.count %}
        <tr>
            <td colspan="4" style="text-align: center"><span class="warning">This cart is empty!</span></td>
        </tr>
        {% endif %}
        <tr>
            <td colspan="2">
                <input type="submit" value="Update Cart" />
            </td>
            <th style="text-align: right">
                Subtotal:
            </th>
            <td>
                ${{ cart.get_total }}
            </td>
        </tr>
    </tbody>
</form>
    <tfoot>
        <tr>
            <td colspan="4">
                <div id="checkout">
                    <!-- Level 1 Integration -->
                    <form action="." method="get">

                        <input type="hidden" name="action" value="checkout" />
                        <input type="image" src="{{ cart.get_cart.button|escape|safe }}" />
                    </form>
                    <!-- Level 2 Integration
                    {{ cart.get_cart.html|safe }}-->
                </div>
            </td>
        </tr>
    </tfoot>
</table>
{% endblock %}

templates/store/cart_detail_limited.html
{% extends "store/base.html" %}

{% block title %}Cart: {{ cart.name }}{% endblock %}

{% block header %}{{ cart.owner.get_full_name }}'s Cart: {{ cart.name }} - {{ cart.get_local_status_display }}{% endblock %}

{% block content %}
{% include "store/limited_cart_table.inc" %}
{% endblock %}

templates/store/cart_form.html
{% extends "store/base.html" %}

{% block title %}New Cart{% endblock %}

{% block header %}Create a new cart{% endblock %}

{% block content %}
<form id="new-cart" action="." method="post">
    <p>
        <label for="newname">New cart name (optional)</label>
        <input type="text" maxlength="125" name="newname" id="newname" />
    </p>
    <p>
        <label for="shared">Share this cart? (optional)</label>
        <input type="checkbox" name="shared" />
    </p>
    <p>
        <input type="submit" value="Create cart" />
    </p>
</form>
{% endblock %}

templates/store/cart_list.html
{% extends "store/base.html" %}

{% block title %}Your Carts{% endblock %}

{% block header %}Your carts{% endblock %}

{% block content %}
{% ifequal user.cart_set.count 0 %}
You have no carts!  <a href="/store/">Time to start shopping!</a>
{% else %}
{% ifnotequal cart_list.count 5 %}
<a id="newcart" href="/store/cart/add/">Create a new cart.</a>
{% endifnotequal %}
<table>
    <tbody>
        {% for cart in cart_list %}
        <tr class="{% cycle 'odd' 'even' %}">
            <td><a href="/store/cart/{{ cart.id }}/">{{ cart.name }}</a> <em>({% if cart.is_shared %}public{% else %}private{% endif %}{% if cart.is_active %}, active{% endif %})</em><br />
                <span class="product-metadata">{{ cart.item_set.count }} item{{ cart.item_set.count|pluralize }} totaling ${{ cart.get_total }}</span></td>
            <td><a href="/store/cart/{{ cart.id }}/?action=delete">Delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endifequal %}
{% endblock %}

templates/store/no_products.html
{% extends "store/base.html" %}

{% block title %}{% block header %}Products{% endblock %}{% endblock %}

{% block content %}
<p class="warning">No products match those criteria.</p>
{% endblock %}

templates/store/product_detail.html
{% extends "store/base.html" %}
{% load tagging_tags %}

{% block title %}{{ product.name }}{% endblock %}

{% block header %}{{ product }}{% endblock %}

{% block content %}

<div id="meta">
    <h3 id="creator"><a href="/store/creator/{{ product.creator.user.username }}/">{{ product.creator.user.get_full_name }}</a></h3>
    <p>{{ product.short_desc }}</p>
    <dl id="product-meta">
        <dt>MJS-MP#</dt>
        <dd>{{ product.sku }}</dd>

        <dt>Pages</dt>
        <dd>{{ product.pages }}</dd>
        {% if product.duration %}
        <dt>Duration</dt>
        <dd>Approx. {{ product.get_duration_display }} (~{{ product.duration }} minutes)</dd>
        {% endif %}
        <dt>Difficulty</dt>
        <dd><a href="/store/products/difficulty/#{{ product.difficulty }}">{{ product.get_difficulty_display }}</a></dd>

        <dt>Category</dt>
        <dd><a href="/store/products/category/{{ product.category }}">{{ product.get_category_display }}</a></dd>
        {% if product.ensemble %}
        <dt>Ensemble</dt>
        <dd><a href="/store/products/ensemble/{{product.ensemble }}/">{{ product.ensemble }}</a></dd>
        {% endif %}
        {% if product.instrumentation %}
        <dt>Instrumentation</dt>
        <dd><a href="/store/products/instrumentation/{{ product.instrumentation }}/">{{ product.instrumentation }}</a></dd>
        {% endif %}
        <dt class="tags">Tags</dt>
        <dd class="tags">{% tags_for_object product as tags %}{% for tag in tags %}<span class="tag-{{ tag.font_size }}"><a href="/store/products/tag/{{ tag.name|slugify }}">{{ tag.name }}</a></span>{% if forloop.last %}.{% else %}, {% endif %}{% endfor %}</dd>
    </dl>
</div>

<div class="long-desc">
    <p><strong>Price:</strong> ${{ product.price }}</p>
    {{ product.long_desc|safe|linebreaks }}
    {% if product.sample_set.count %}
    <dl>
        {% for sample in product.sample_set.all %}
        <dt>{{ sample.get_type_display }}</dt>
        <dd>{{ sample.html|safe }}</dd>
        {% endfor %}
    </dl>
    {% endif %}
</div>

<div id="add-form">
    {% if user.is_authenticated %}
    {% ifequal product.status '0' %}
    <strong>Add to cart:</strong>
    <form action="." method="post">
        <label for="quantity">Quantity:</label>
        <input type="text" size="3" name="quantity" id="quantity" />
        <input type="submit" value="Add to cart" />
    </form>
    {% else %}
    <span class="error">{{ product.get_status_display }}</span>
    {% endifequal %}
    {% else %}
    <a href="/accounts/login/?next={{ request.path }}">Please log in to shop for this and other products!</a>
    {% endif %}
</div>


{% endblock %}

templates/store/product_list.html
{% extends "store/base.html" %}
{% load tagging_tags %}

{% block title %}Products{% endblock %}

{% block header %}Products{% endblock %}

{%block content %}
<div id="product-filters">
    {% if not tag %}
    <p>{{ filter_by|title }}: {{ filter }} </p>
    {% else %}
    <p>With tag: {{ tag }}</p>
    {% endif %}
    {% if is_paginated %}<p>Showing items {{ page_obj.start_index }} through {{ page_obj.end_index }}</p>{% endif %}
</div>

<table id="product-list">
    <thead>
        <tr>
            <th style="text-align: left">Product</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        {% if is_paginated %}
        {% for product in page_obj.object_list %}
        <tr class="{% cycle 'odd' 'even' %}">
            <td class="product-info"><strong><a href="/store/product/{{ product.sku }}/">{{ product.name }}</a></strong> - {{ product.creator.user.get_full_name }}<br />
                {{ product.short_desc }}<br />
                <span class="product-metadata">
                    Instrumentation: <a href="/store/product/instrumentation/{{ product.instrumentation }}/">{{ product.instrumentation }}</a> |
                    Difficulty: {{ product.get_difficulty_display }} |
                    Tags: {% tags_for_object product as tags %}{% for tag in tags %}<a href="/store/products/tag/{{ tag.name|slugify }}/">{{ tag.name }}</a>{% if forloop.last %}.{% else %}, {% endif %}{% endfor %}
                </span>
            </td>
            <td class="product-price">
                {% ifequal product.status '0' %}${{ product.price }}{% else %}{{ product.get_status_display }}{% endifequal %}
            </td>
        </tr>
        {% endfor %}
        {% else %}
        {% for product in product_list %}
        <tr class="{% cycle 'odd' 'even' %}">
            <td class="product-info"><strong><a href="/store/product/{{ product.sku }}/">{{ product.name }}</a></strong> - {{ product.creator.user.get_full_name }}<br />
                {{ product.short_desc }}<br />
                <span class="product-metadata">
                    Instrumentation: {{ product.instrumentation }} |
                    Difficulty: {{ product.get_difficulty_display }} |
                    Tags: {% tags_for_object product as tags %}{% for tag in tags %}<a href="/store/products/tag/{{ tag.name|slugify }}/">{{ tag.name }}</a>{% if forloop.last %}.{% else %}, {% endif %}{% endfor %}
                </span>
            </td>
            <td class="product-price">
                {% ifequal product.status '0' %}${{ product.price }}{% else %}{{ product.get_status_display }}{% endifequal %}
            </td>
        </tr>
        {% endfor %}
        {% endif %}
    </tbody>
    {% if is_paginated %}
    <tfoot>
        <tr>
            <td colspan="2" style="text-align: center">
                {% if page_obj.has_previous %}<a href="{{ request.path }}?page=1&paginate_by={{ paginate_by }}">&lt;&lt;</a> &bull; <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}&paginate_by={{ paginate_by }}">&lt {{ page_obj.previous_page_number }}</a> &bull; {% endif %}<strong>{{ page_obj }}</strong>{% if page_obj.has_next %} &bull; <a href="{{ request.path }}?page={{ page_obj.next_page_number }}&paginate_by={{ paginate_by }}">{{ page_obj.next_page_number }} &gt;</a> &bull; <a href="{{ request.path }}?page=last&paginate_by={{ paginate_by }}">&gt;&gt;</a>{% endif %}<br />
                <form method="get" action=".">
                    <label for="paginate_by">Items per page:</label>
                    <select name="paginate_by" id="paginate_by">
                        <option value="5">5</option>
                        <option value="10">10</option>
                        <option value="15">15</option>
                        <option value="25" selected="selected">25</option>
                        <!--<option value="50">50</option>
                        <option value="100">100</option>-->
                    </select>
                    <input type="submit" value="Go" />
                </form>
            </td>
        </tr>
    </tfoot>
    {% endif %}
</table>
{% endblock %}