forum/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('forum.views',
        (r'^pm/$', 'list_pms'),
        (r'^pm/(?P<post>\d+)/$', 'view_pm'),
        (r'^pm/(?P<post>\d+)/reply/$', 'reply_to_pm'),
        (r'^pm/(?P<post>\d+)/read/$', 'mark_pm_as_read'),
        (r'^pm/(?P<user>[-_a-zA-Z0-9]+)/$', 'start_pm'),
        (r'^signature/$', 'edit_sig'),

        (r'^$', 'view_forum'),
        (r'^(?P<forum>[-_a-z0-9]+)/$', 'view_forum'),
        (r'^(?P<forum>[-_a-z0-9]+)/post/$', 'post_topic'),
        (r'^(?P<forum>[-_a-z0-9]+)/(?P<post>\d+)/$', 'view_topic'),
        (r'^(?P<forum>[-_a-z0-9]+)/(?P<post>\d+)/reply/$', 'post_reply'),
        (r'^(?P<forum>[-_a-z0-9]+)/(?P<post>\d+)/edit/$', 'edit_topic'),
        (r'^(?P<forum>[-_a-z0-9]+)/(?P<post>\d+)/delete/$', 'delete_topic'),
        )

urls.py
from django.conf.urls.defaults import *
from store.models import *
from sitemaps import *
from django.contrib.sitemaps import FlatPageSitemap
from django.contrib import admin
admin.autodiscover()

sitemaps = {
        'products': ProductSitemap,
        'creators': CreatorSitemap,
        }

urlpatterns = patterns('',
    (r'^$', 'blog.views.front'),
    (r'^crossdomain.xml$', 'django.views.generic.simple.direct_to_template', {'template': 'flatpages/crossdomainpolicy.xml'}),
    (r'^sitemap.xml$', 'django.views.generic.simple.direct_to_template', {'template': 'flatpages/sitemap.xml'}),
    (r'^sitemap-other.xml$', 'django.views.generic.simple.direct_to_template', {'template': 'flatpages/sitemap-other.xml'}),
    (r'^sitemap-store.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    (r'^sitemap-flatpages.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': { 'flatpages': FlatPageSitemap }}),
    (r'^store/$', 'blog.views.storefront'),
    (r'^~(?P<username>[-_a-zA-Z0-9]+)/$', 'store.views.creator_detail'),
    (r'^~(?P<filter>[-_a-zA-Z0-9]+)/products/$', 'store.views.filter_products', {'filter_by': 'creator__user__username__iexact'}),
    (r'^store/', include('store.urls')),
    (r'^portfolio/', include('portfolio.urls')),
    (r'^admin/(.*)', admin.site.root),
    (r'^forums/', include('forum.urls')),

    (r'^accounts/view/(?P<username>[-_a-zA-Z0-9]+)/$', 'usermgmt.views.user_view'),
    (r'^accounts/interest/(?P<tag>[-_a-zA-Z0-9]+)/$', 'usermgmt.views.with_tags'),
    (r'^accounts/profile/$', 'usermgmt.views.user_home'),
    (r'^accounts/profile/edit/$', 'usermgmt.views.user_edit'),
    (r'^accounts/', include('registration.urls')),
    (r'^about/contact/$', 'usermgmt.views.contact')
)
        ##(r'^store/products/difficulties/$', 'difficulties') # FLATPAGE - template: store/about_flatpages.html
        ##(r'^store/products/categories/$', 'categories'), # FLATPAGE - template: store/about_flatpages.html
        ##(r'^store/products/tags/$', 'tag_cloud'), # FLATPAGE - template: store/tags.html
        ##(r'^account/interests/$', tag_cloud) # FLATPAGE - template: registration/tags.html
        #(r'^about/$') # FLATPAGE - template: flatpages/about.html
        #(r'^about/faq/$') # FLATPAGE - template: flatpages/about.html
        #(r'^about/submit/$') # FLATPAGE - template: flatpages/about.html
        #(r'^about/legal/$') # FLATPAGE - template: flatpages/about.html
        #(r'^about/ip/$') # FLATPAGE - template: flatpages/about.html
        #(r'^store/about/shipping/$') # FLATPAGE - template: flatpages/about.html
        #(r'^store/about/problems/$') # FLATPAGE - template: flatpages/about.html

forum/models.py
from django.db import models
from django.contrib.auth.models import User

class ForumUser(models.Model):
    user = models.OneToOneField(User, primary_key = True)
    signature = models.TextField(blank = True)

class Forum(models.Model):
    slug = models.SlugField(primary_key = True)
    name = models.CharField(max_length = 120)
    description = models.CharField(max_length = 500)
    parent = models.ForeignKey('Forum', blank = True, null = True)
    moderators = models.ManyToManyField(User)
    users_can_post = models.BooleanField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        if self.slug == '__root__':
            return '/forums/'
        else:
            return '/forums/%s/' % self.slug

class Post(models.Model):
    forum = models.ForeignKey('Forum')
    parent = models.ForeignKey('Post', blank = True, null = True)
    owner = models.ForeignKey(User)
    is_sticky = models.BooleanField()
    users_can_reply = models.BooleanField(default = True)
    title = models.CharField(max_length = 250)
    body = models.TextField()
    ctime = models.DateTimeField(auto_now_add = True)
    mtime = models.DateTimeField(auto_now = True)
    muser = models.ForeignKey(User, blank = True, null = True, related_name = 'modified_post')
    mreason = models.CharField(max_length = 250, blank = True, null = True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-is_sticky', 'ctime']

class PM(models.Model):
    user_to = models.ForeignKey(User, related_name = 'user_to')
    user_from = models.ForeignKey(User, related_name = 'user_from')
    parent = models.ForeignKey('PM', blank = True, null = True)
    title = models.CharField(max_length = 250)
    body = models.TextField()
    ctime = models.DateTimeField(auto_now_add = True)
    is_read = models.BooleanField()

    def __unicode__(self):
        return self.title

    def has_unread(self):
        to_ret = not self.is_read
        for p in self.pm_set.all():
            # check for unread PMs
            to_ret = to_ret or not p.is_read
        return to_ret

    class Meta:
        ordering = ['ctime']

store/models.py
from django.db import models
from django.contrib.auth.models import User
from store.checkout import get_controller
from tagging.fields import TagField

class Creator(models.Model):
    user = models.ForeignKey(User)
    profile = models.TextField()
    website = models.URLField(blank = True)

    def __unicode__(self):
        return self.user.get_full_name()

    def get_absolute_url(self):
        return "/store/creator/%s/" % self.user.username

class Product(models.Model):
    # Checkout stuff
    STATUS_CHOICES = (
            ('0', 'Live'),
            ('1', 'Coming Soon'),
            ('2', 'Out-of-Print'),
            ('3', 'Hidden')
            )

    sku = models.SlugField()
    status = models.CharField(max_length = 1, choices = STATUS_CHOICES)
    name = models.CharField(max_length = 250)
    short_desc = models.CharField(max_length = 500)
    width = models.DecimalField(max_digits = 3, decimal_places = 1)
    length = models.DecimalField(max_digits = 3, decimal_places = 1)
    height = models.DecimalField(max_digits = 3, decimal_places = 1)
    weight = models.DecimalField(max_digits = 3, decimal_places = 1)
    price = models.DecimalField(max_digits = 6, decimal_places = 2)

    # Product stuff
    DIFFICULTY_CHOICES = (
            ('1', 'Grade 1'),
            ('2', 'Grade 2'),
            ('3', 'Grade 3'),
            ('4', 'Grade 4'),
            ('5', 'Grade 5'),
            ('6', 'Grade 6'),
            ('7', 'Grade 7')
            )

    CATEGORY_CHOICES = (
            ('A', 'Concert'),
            ('B', 'Sacred'),
            ('C', 'Occasional'),
            ('D', 'Educational'),
            ('E', 'Jazz'),
            ('F', 'Pop/Rock'),
            ('G', 'Textbooks/Classroom Materials'),
            ('H', 'Other')
            )

    long_desc = models.TextField()
    creator = models.ForeignKey('Creator')
    pages = models.IntegerField()
    duration = models.DecimalField(max_digits = 4, decimal_places = 1)
    difficulty = models.CharField(max_length = 1, choices = DIFFICULTY_CHOICES)
    category = models.CharField(max_length = 1, choices = CATEGORY_CHOICES)
    ensemble = models.CharField(max_length = 120)
    instrumentation = models.CharField(max_length = 120)
    tags = TagField()

    def get_unique(self, field):
        # this is bad, but it works
        from django.db import connection
        cursor = connection.cursor()
        cursor.execute("select distinct " + field.split(' ')[0] + " from store_product")
        if cursor.rowcount == -1:
            return None
        else:
            rows = cursor.fetchall()
            for i in range(0,len(rows)):
                rows[i] = str(rows[i][0])
            return rows

    def get_duration_display(self):
        import math
        hours = 0
        minutes = 0
        seconds = 0
        if self.duration > 60:
            hours = int(math.floor(self.duration / 60))
        minutes = int(math.floor(self.duration))
        seconds = int(60 * (self.duration - minutes))
        return "%02d:%02d:%02d" % (hours, minutes, seconds)

    def __unicode__(self):
        return "MJS-MP#%(sku)s - %(name)s" % {'sku': self.sku, 'name': self.name}

    def get_absolute_url(self):
        return "/store/product/%s/" % self.sku

    class Meta:
        ordering = ['sku']

class Sample(models.Model):
    TYPE_CHOICES = (
            ('A', 'Audio sample'),
            ('D', 'Page sample'),
            ('V', 'Video sample'),
            ('E', 'External sample'),
            )
    product = models.ForeignKey('Product')
    type = models.CharField(max_length = 1, choices = TYPE_CHOICES)
    url = models.URLField()

    def __unicode__(self):
        return "%s - %s" % (self.product, self.get_type_display())

    def html(self):
        ext = self.url[len(self.url) - 3:]
        if ext == 'mp3':
            return '<embed src="http://media.mjs-publishing.com/mediaplayer.swf" width="470" height="20" allowscriptaccess="always" allowfullscreen="true" flashvars="height=20&width=470&file=%s" />' % self.url
        elif ext == 'pdf':
            return '<a target="_blank" href="%s"><img src="http://media.mjs-publishing.com/pdfData/pdficon_large.gif" alt="[PDF]" width="20" /> [View Document]</a><br />Requires Adobe Reader:<br /><a href="http://get.adobe.com/reader/"><img src="http://media.mjs-publishing.com/pdfData/get_adobe_reader.gif" alt="[get Adobe Reader]" /></a>' % self.url
        else:
            return '<a target="_blank" href="%s">External Sample</a>' % self.url

        class Meta:
            ordering = ['id']

class Item(models.Model):
    cart = models.ForeignKey('Cart')
    product = models.ForeignKey('Product')
    quantity = models.IntegerField()

class Cart(models.Model):
    STATUS_CHOICES = (
            ('0', 'Finished Shopping'),
            ('1', 'Still Shopping'),
            ('2', 'System Error'),
            ('3', 'User reported problem'),
            ('4', 'Offline Order'),
            )

    owner = models.ForeignKey(User)
    name = models.CharField(max_length = 125)
    is_active = models.OneToOneField(User, null = True, blank = True, related_name = 'active_cart')
    is_shared = models.BooleanField(default = False)
    ctime = models.DateTimeField(auto_now_add = True, blank = False)
    mtime = models.DateTimeField(auto_now = True, blank = False)
    local_status = models.CharField(max_length = 1, choices = STATUS_CHOICES)
    state = models.CharField(max_length = 16, blank = True)
    payment = models.CharField(max_length = 16, blank = True)
    google_id = models.CharField(max_length = 255, blank = True)
    cart_xml = models.TextField(blank = True)
    
    
    def get_cart(self):
        from gchecky.model import *
        controller = get_controller()

        return controller.prepare_order(
                order = checkout_shopping_cart_t(
                    shopping_cart = shopping_cart_t(
                        items = [
                            item_t(
                               name = item.product.name,
                               description = item.product.short_desc,
                               unit_price = price_t(
                                   value = float(item.product.price),
                                   currency = 'USD'
                                   ),
                               item_weight = item_weight_t(
                                   value = float(item.product.weight),
                                   unit = 'LB'
                                   ),
                               quantity = item.quantity,
                               merchant_item_id = item.product.sku
                               ) for item in self.item_set.all()
                            ],
                        merchant_private_data = self.id
                        ),
                    checkout_flow_support = checkout_flow_support_t(
                        #XXX
                        edit_cart_url = 'http://sandbox.mjs-publishing.com/store/cart/%s/?action=decheckout' % self.id,
                        continue_shopping_url = 'http://sandbox.mjs-publishing.com/store/',
                        #/XXX
                        #tax_tables = tax_tables_t(
                        #    merchant_calculated = False,
                        #    default = default_tax_table_t(
                        #        tax_rules = [
                        #            default_tax_rule_t(
                        #                shipping_taxed = True,
                        #                rate = 0.059,
                        #                tax_area = tax_area_t(
                        #                    us_zip_pattern = '805*'
                        #                    )
                        #                ),
                        #            default_tax_rule_t(
                        #                shipping_taxed = True,
                        #                rate = 0.029,
                        #                tax_area = tax_area_t(
                        #                    us_state = 'CO'
                        #                    )
                        #                )
                        #            ]
                        #        )
                        #    ),
                        shipping_methods = shipping_methods_t(
                            carrier_calculated_shippings = [
                                carrier_calculated_shipping_t(
                                    carrier_calculated_shipping_options = [
                                        carrier_calculated_shipping_option_t(
                                            price = price_t(
                                                value = (self.total_weight() * 2 + 3),
                                                currency = 'USD'
                                                ),
                                            shipping_company = 'USPS',
                                            carrier_pickup = 'DROP_OFF',
                                            shipping_type = 'Priority Mail'
                                            ),
                                        carrier_calculated_shipping_option_t(
                                            price = price_t(
                                                value = (self.total_weight() * 0.5 + 6.79),
                                                currency = 'USD'
                                                ),
                                            shipping_company = 'FedEx',
                                            carrier_pickup = 'DROP_OFF',
                                            shipping_type = 'Ground'
                                            )
                                        ],
                                    shipping_packages = [
                                        shipping_package_t(
                                            height = measure_t(

forum/forms.py
from django import forms

class PostForm(forms.Form):
    title = forms.CharField(max_length = 250, required = False)
    body = forms.CharField(widget = forms.Textarea)

class PostEditForm(forms.Form):
    title = forms.CharField(max_length = 250, required = False)
    body = forms.CharField(widget = forms.Textarea)
    reason = forms.CharField(max_length = 250, required = False)

templates/forum/base.html
{% extends "base.html" %}

{% block section %}Forum{% endblock %}

{%block sectionlinks %}
<link rel="stylesheet" type="text/css" href="http://media.mjs-publishing.com/css/forum.css" />
{% if user.is_authenticated %}
{% ifnotequal user.active_cart '' %}
<div id="cart-control">
    Your active cart: <a href="/store/cart/{{ user.active_cart.id }}/">${{ user.active_cart.get_total }}</a>
</div>
{% endifnotequal %}
{% endif %}
<ul>
    <li><a href="/forums/">Forum Home</a></li>
    {% if user.is_authenticated %}<li><a href="/forums/pm/">Private Messages</a></li>
    <li><a href="/forums/signature/">Edit Signature</a></li>{% endif %}
</ul>
{% endblock %}

templates/forum/base_minimal.html
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
    	<link rel="icon" type="image/png" href="http://media.mjs-publishing.com/icon.png" />
	    <link rel="stylesheet" href="http://media.mjs-publishing.com/css/base.css" type="text/css" media="screen" />
    	<link rel="stylesheet" href="http://media.mjs-publishing.com/css/print.css" type="text/css" media="print" />
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/forum/edit_sig.html
{% extends "forum/base.html" %}

{% load bbcode %}

{% block title %}{% block header %}Edit user signature{% endblock %}{% endblock %}

{% block content %}
<form method="post">
    <table>
        <thead>
            <tr>
                <th><strong>Preview:</strong></th>
                <td><p>{{ user.forumuser.signature|striptags|bbcode|safe }}</p></td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th><label for="signature">Signature</label></th>
                <td><textarea name="signature" rows="10" cols="40">{{ sig }}</textarea></td>
            </tr>
            <tr>
                <th colspan="2"><input type="submit" value="Update signature" /></th>
            </tr>
        </tbody>
    </table>
</form>
{% endblock %}

templates/forum/forum_detail.html
{% extends "forum/base.html" %}

{% load bbcode %}
{% load forumtree %}

{% block title %}{% block header %}{{ forum.name }}{% endblock %}{% endblock %}

{% block content %}
{% if forum.parent %}{% ifnotequal forum.parent "__root__" %}
<p><a href="/forums/{{ forum.parent.slug }}/">&larr; Back to <em>{{ forum.parent.name }}</em></a></p>
{% endifnotequal %}{% endif %}
{% if forum.users_can_post %}
<p style="text-align: center"><form action="post/"><input type="submit" value="New Topic" /></form></p><br />
{% endif %}
<table id="forum">
    {% if posts %}
    <tr>
        <th>Post</th>
        <th width="10%">Replies</th>
    </tr>
    {% for post in posts %}
    <tr class="{% cycle "odd" "even" %}">
        <td><strong><a href="/forums/{{ post.forum.slug }}/{{ post.id }}/">{{ post.title }}</a></strong> -
            {% if post.owner.creator_set %}<a style="font-size: 75%" href="/store/creator/{{ post.owner.username }}/">{{ post.owner.get_full_name }}</a>
            {% else %}{{ post.owner.username }}{% endif %}<br />
            <p style="font-size: 75%">{{ post.body|striptags|stripbb|truncatewords_html:15|safe }}</p></td>
        <td class="pcount">{{ post.post_set.count }}</td>
    </tr>
    {% endfor %}
    {% if forum.forum_set.all %}
    <tr>
        <td colspan="2"><hr /></td>
    </tr>
    {% endif %}
    {% endif %}
    {% if forum.forum_set.all %}
    <tr>
        <th>Forum</th>
        <th width="10%">Post Count</th>
    </tr>
    {{ forum|forumtree }}
    {% endif %}
</table>
{% if forum.users_can_post %}
<p style="text-align: center"><form action="post/"><input type="submit" value="New Topic" /></form></p>
{% endif %}
{% endblock %}

templates/forum/list_pms.html
{% extends "forum/base.html" %}

{% load bbcode %}

{% block title %}{% block header %}Private Messages{% endblock %}{% endblock %}

{% block content %}
<table id="forum">
    <thead>
        <tr>
            <th>Private Message</th>
            <th>Posts</th>
        </tr>
    </thead>
    {% for pm in pms %}
    {% if pm.has_unread %}
    <tr class="unread">
    {% else %}
    <tr class="{% cycle "odd" "even" %}">
    {% endif %}
        <td><strong><a href="/forums/pm/{{ pm.id }}/">{{ pm.title }}</a></strong> -
            {% if pm.user_from.creator_set %}<a style="font-size: 75%" href="/store/creator/{{ pm.user_from.username }}/">{{ pm.user_from.get_full_name }}</a>
            {% else %}{{ pm.user_from.username }}{% endif %} &rarr;
            {% if pm.user_to.creator_set %}<a style="font-size: 75%" href="/store/creator/{{ pm.user_to.username }}/">{{ pm.user_to.get_full_name }}</a>
            {% else %}{{ pm.user_to.username }}{% endif %}<br />
            <p style="font-size: 75%">{{ pm.body|striptags|truncatewords:25|bbcode|safe }}</p></td>
        <td>{{ pm.pm_set.count }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

templates/forum/pm_detail_minimal.html
{% extends "forum/base_minimal.html" %}

{% load bbcode %}

{% block title %}{% block header %}{{ post.title }}{% endblock %}{% endblock %}

{% block content %}
<table id="forum">
    <thead>
        <tr>
            <th width="25%">User</th>
            <th>Private Message</th>
        </tr>
    </thead>
    <tbody>
        <tr class="odd">
            <td><div class="forum-poster"><a name="{{ post.id }}"><strong>
                {% if post.owner.creator_set %}<a href="/store/creator/{{ post.owner.username }}/">{{ post.owner.get_full_name }}</a>
                {% else %}{{ post.owner.username }}{% endif %}
            </strong></a></div></td>
            <td><div class="post-header"><strong>{{ post.title }}</strong></div>
                <div class="post-body">{{ post.body|striptags|bbcode|safe }}</div></td>
        </tr>
        {% for p in post.post_set.all %}
        <tr class="{% cycle "even" "odd" %}">
            <td><div class="forum-poster"><a name="{{ p.id }}"><strong>
                {% if p.owner.creator_set %}<a href="/store/creator/{{ p.owner.username }}/">{{ p.owner.get_full_name }}</a>
                {% else %}{{ p.owner.username }}{% endif %}
            </strong></a></div></td>
            <td><div class="post-header"><abbr text="In reply to {{ post.title }}">{{ p.title }}</abbr></div>
                <div class="post-body">{{ p.body|striptags|bbcode|safe }}</div></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/forum/pm_post_form.html
{% extends "forum/base.html" %}

{% block title %}{% block header %}New Private Message{% endblock %}{% endblock %}

{% block content %}
<form method="post">
<table width="100%">
    <thead>
        <tr>
            <th colspan="2">Private message to {{ user_to }}</th>
    <tbody>
        <tr>
            <th width="25%"><label for="title">Title</label></th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th><label for="body">Body</label></th>
            <td>{{ form.body }}</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <th colspan="2">
                <input type="submit" value="Send PM" />
            </th>
        </tr>
    </tfoot>
</table>
</form>
{% endblock %}

templates/forum/post_detail.html
{% extends "forum/base.html" %}

{% load bbcode %}

{% block title %}{% block header %}{{ post.title }}{% endblock %}{% endblock %}

{% block content %}
<p><a href="/forums/{{ post.forum.slug }}">&larr; Back to <em>{{ post.forum.name }}</em></a></p>
<table id="forum">
    <thead>
        <tr>
            <th width="25%">User</th>
            <th>Post</th>
        </tr>
    </thead>
    <tbody>
        <tr class="odd">
            <td>
                <div class="forum-poster"><a name="{{ post.id }}"> </a><strong>
                    {% if post.owner.creator_set %}<a href="/store/creator/{{ post.owner.username }}/">{{ post.owner.get_full_name }}</a>
                    {% else %}{{ post.owner.username }}{% endif %}
                    </strong> <span style="font-size: 75%"><a href="/forums/pm/{{ post.owner.username }}/">Send PM</a></span>
                </div>
                <div class="post-time">{{ post.ctime|date:"r" }}</div>
            </td>
            <td>
                <div class="post-header"><strong>{{ post.title }}</strong></div><div class="post-controls">[ 
                    <a href="/forums/{{ post.forum.slug }}/{{ post.id }}/reply?reply-to={{ post.id }}">Quote</a> | 
                    <a href="/forums/{{ post.forum.slug }}/{{ post.id }}/edit">Edit</a> | 
                    <a href="/forums/{{ post.forum.slug }}/{{ post.id }}/delete/">Delete</a> ]
                </div>
                <div class="post-body">{{ post.body|striptags|bbcode|safe }}</div>
                {% if post.mreason %}
                <div class="post-edits">
                    <p>Edited: <em>{{ post.mtime|date:"r" }}</em> by <em>{{ post.muser.username }}</em><br />
                    Reason: <em>{{ post.mreason }}</em></p>
                </div>
                {% endif %}
                <div class="post-sig">
                    {{ post.owner.forumuser.signature|striptags|bbcode|safe }}
                </div>
            </td>
        </tr>
        {% for p in post.post_set.all %}
        <tr class="{% cycle "even" "odd" %}">
            <td><div class="forum-poster"><a name="{{ p.id }}"> </a><strong>
                    {% if p.owner.creator_set %}<a href="/store/creator/{{ p.owner.username }}/">{{ p.owner.get_full_name }}</a>
                    {% else %}{{ p.owner.username }}{% endif %}
                    </strong> <span style="font-size: 75%"><a href="/forums/pm/{{ p.owner.username }}/">Send PM</a></span>
                </div>
                <div class="post-time">{{ p.ctime|date:"r" }}</div>
            </td>
            <td>
                <div class="post-header"><abbr title="In reply to {{ post.title }}"><strong>{{ p.title }}</strong></abbr></div><div class="post-controls">[ 
                    <a href="/forums/{{ post.forum.slug }}/{{ post.id }}/reply?reply-to={{ p.id }}">Quote</a> | 
                    <a href="/forums/{{ post.forum.slug }}/{{ p.id }}/edit">Edit</a> | 
                    <a href="/forums/{{ post.forum.slug }}/{{ p.id }}/delete/">Delete</a> ]
                </div>
                <div class="post-body">{{ p.body|striptags|bbcode|safe }}</div>
                {% if p.mreason %}
                <div class="post-edits">
                    <p>Edited: <em>{{ p.mtime|date:"r" }}</em> by <em>{{ p.muser.username }}</em><br />
                    Reason: <em>{{ p.mreason }}</em></p>
                </div>
                {% endif %}
                <div class="post-sig">
                    {{ p.owner.forumuser.signature|striptags|bbcode|safe }}
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th colspan="2">
                <form action="/forums/{{ post.forum.slug }}/{{ post.id }}/reply/">
                    <input type="submit" value="Reply" />
                </form>
            </th>
        </tr>
    </tfoot>
</table>
{% endblock %}

templates/forum/post_detail_minimal.html
{% extends "forum/base_minimal.html" %}

{% load bbcode %}

{% block title %}{% block header %}{{ post.title }}{% endblock %}{% endblock %}

{% block content %}
<table id="forum" style="width: 100%">
    <thead>
        <tr>
            <th width="20%">User</th>
            <th>Post</th>
        </tr>
    </thead>
    <tbody>
        <tr class="odd">
            <td><div class="forum-poster"><a name="{{ post.id }}"><strong>
                {% if post.owner.creator_set %}<a href="/store/creator/{{ post.owner.username }}/">{{ post.owner.get_full_name }}</a>
                {% else %}{{ post.owner.username }}{% endif %}
            </strong></a></div></td>
            <td><div class="post-header"><strong>{{ post.title }}</strong></div>
                <div class="post-body">{{ post.body|striptags|bbcode|safe }}</div></td>
        </tr>
        {% for p in post.post_set.all %}
        <tr class="{% cycle "even" "odd" %}">
            <td><div class="forum-poster"><a name="{{ p.id }}"><strong>
                {% if p.owner.creator_set %}<a href="/store/creator/{{ p.owner.username }}/">{{ p.owner.get_full_name }}</a>
                {% else %}{{ p.owner.username }}{% endif %}
            </strong></a></div></td>
            <td><div class="post-header"><abbr text="In reply to {{ post.title }}">{{ p.title }}</abbr></div>
                <div class="post-body">{{ p.body|striptags|bbcode|safe }}</div></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}